### ISSUE TITLE
Issues with indentation/scope

### ISSUE THREAD

**Issue by zedzee37** [GDQuest/zed-gdscript#10]
## Tested Versions ##
- Zed v0.143.7
- GDScript v0.2.0
- Godot Engine v4.3.beta2.mono.official.b75f0485b

## System Information ##
Ubuntu 24.04 LTS

## Issue Description ##
When using this extension, the indentation of the code is often lost, specifically with for loops or if statements, where it just goes to the start of the line or the indentation level of the function.

## Steps to Reproduce ##
Writing code such as:
```gdscript
func foo() -> void:
	for i in range(5):
```
and creating a new line results in the indentation level being lost.

**Comment by zedzee37** [comment]
I should note that I have 'hard tabs' enabled for GDScript, simply to follow Godot's usage of tabs instead of spaces, but the same issue occurs when using spaces (and enabling spaces on the Godot side).

**Comment by NathanLovato** [comment]
Reopening because the attempted fix introduced other issues. The original queries for indent are going in a good direction, they just need to be refined to account for new cases.

**Comment by NathanLovato** [comment]
Here are issues that I can spot right now:

- Generally, indents in inner classes or functions only work if there's a statement below the code you're adding in the same block.
- After the start of a block, no indent is added.
- After a method  definition or static function definition.

**Comment by NathanLovato** [comment]
Found the cause and a fix, Zed has some settings that don't seem to be documented that we kinda need to use for an indent-based language. I couldn't get indentation working great with tree sitter queries, but they're working well with these settings now.
