### ISSUE TITLE
Outline move for script symbols

### ISSUE THREAD

**Issue by ygingras** [GDQuest/zed-gdscript#12]
It would be great to have the outline and be able to jump to any of the symbols defined in a GDScript file like the build-in Godot editor does or even the godot-tools extension for VS Code.

**Comment by NathanLovato** [comment]
I just added support for inner classs and functions to the outline in the development version of the extension. What other symbols would you like to be able to see in the outline? Do you want all properties, enums, constants? For inner classes too? Can you think of something else?

![image](https://github.com/user-attachments/assets/56f70a26-9495-449d-9843-aa3a4835b22e)

**Comment by ygingras** [comment]
Looks great! 

One big one would be the signals since they are part of the public API of a Node.

**Comment by NathanLovato** [comment]
Thanks! Here's where I'm at right now. I still need to wrap my head around this query language as I couldn't find a way to get autocomplete or a clear reference of the available grammar/keywords/whatever.

![image](https://github.com/user-attachments/assets/d7230eb9-b44b-4930-99c1-f1bc76442b5b)

Does this look fine by you? What changes would you expect?

**Comment by ygingras** [comment]
This looks perfect!

**Comment by NathanLovato** [comment]
Cool, closing this then! I'd still like to make some improvements but I'll log a separate issue.
