### ISSUE TITLE
After the beginning of a code block, the next line is not indented

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/zed-gdscript#21]
Here's a video demonstrating this:

https://github.com/user-attachments/assets/ffc6584e-c918-40fc-97e0-199db626d91f

**Comment by fstxz** [comment]
Isn't this the same as #10 ? It was supposed to be fixed in #15

**Comment by NathanLovato** [comment]
It seems to be the same thing, in which case the pull request did not fix the issue. It might have been tested a little too quickly, not finding all edge cases.

**Comment by fstxz** [comment]
I reverted that PR and indentation seem to work only when there is no `:` at the end of the line, interesting.
