### ISSUE TITLE
Does this support symbol search out of the box or does something else need to be configured?

### ISSUE THREAD

**Issue by bs** [GDQuest/zed-gdscript#28]
**What is the current behavior?**

`cmd-t` brings up search project symbols but no results.

**What is the expected behavior?**

A list of symbols in the project to filter.

**Comment by NathanLovato** [comment]
Project symbols are a feature provided by language servers. The GDScript language server does not provide project symbols as far as I know, so this is not something the extension unfortunately cannot offer at the moment. It needs to be contributed to the Godot engine itself: https://github.com/godotengine/godot

**Comment by bs** [comment]
Ah, OK. I'll dig a little deeper.

In Sublime (using the new: https://github.com/dementive/SublimeGodot), `textDocument/documentSymbol` does return results while `workspace/symbol` returns `'code': -32601, 'message': 'Method not found: symbol'`

**Comment by NathanLovato** [comment]
The document symbols are supported, and so is go to definition or find references.

Workspace/project-wide symbols indeed that are not supported by Godot's language server. You can check the source code here if you'd like: https://github.com/godotengine/godot/tree/master/modules/gdscript/language_server

I think the feature would need to be added in https://github.com/godotengine/godot/blob/master/modules/gdscript/language_server/gdscript_workspace.h

**Comment by bs** [comment]
I'll take a look! And found `search-buffer-symbols` with `cmd-shift-o`. Was surprised to not see it in the command palette!

**Comment by ygingras** [comment]
Commenting for posterity: `search-buffer-symbols` is called "outline:toggle" in the command pallet. It's bound to "ctrl-shit-o" by default on Linux.
