### ISSUE TITLE
Mac Getting Started Guide / Setup Instructions

### ISSUE THREAD

**Issue by notpeter** [GDQuest/zed-gdscript#9]
I wrote up some instructions for using this extension here:

https://github.com/zed-industries/zed/issues/13773#issuecomment-2226113020

Might be nice to create a mini setup tutorial with screenshots and such.

P.S. Great job getting this to work with Zed!

**Comment by RustoMCSpit** [comment]
this tutorial is written for macs btw. not linux or windows.

**Comment by NathanLovato** [comment]
Thanks for the suggestion! I rewrote the install instructions in the README and included a line about installing netcat for macOS

**Comment by notpeter** [comment]
Excellent! I rolled my guide into the official Zed language docs the other day too:
https://zed.dev/docs/languages/gdscript. Source here: [gdscript.md](https://github.com/zed-industries/zed/blob/main/docs/src/languages/gdscript.md)

I'm not a GDScript/Godot dev, so please let me know if got anything wrong. Someone pointed out that MacOS actually includes an `nc` by default at `/usr/bin/nc` so I removed that from the MacOS instructions.

Excited to see an additional maintainer!

**Comment by NathanLovato** [comment]
Really cool @notpeter! One thing I would do in the docs is specify that points 4 and 5 in the setup are not about setting up the language support, but specifically about making Godot open the files in zed.
